apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: europe-west1-docker.pkg.dev/{{PROJECT_ID}}/ride-sharing/driver-service
          ports:
            - containerPort: 8082
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - port: 8082
      name: http
      targetPort: 8082
    - port: 9092
      name: grpc
      targetPort: 9092
  type: ClusterIP

